--liquibase formatted sql

--changeset maciekkobierecki:20200123_001_create_domain_tables endDelimiter:/


CREATE TABLE LOANS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
CREATE_DATE TIMESTAMP     NOT NULL,
END_DATE TIMESTAMP     NOT NULL,
AMOUNT NUMERIC(15,2)  NOT NULL,
CONSTRAINT C_LOANS_PK PRIMARY KEY (ID)
)
/

--rollback DROP TABLE LOANS

CREATE TABLE LOAN_PROLONGS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
LOAN_ID INTEGER NOT NULL,
CREATE_DATE TIMESTAMP     NOT NULL,
END_DATE TIMESTAMP     NOT NULL,
PROLONG_PERIOD INTEGER NOT NULL,
CONSTRAINT C_LOAN_PROLONGS_PK PRIMARY KEY (ID)
)
/

ALTER TABLE LOAN_PROLONGS ADD CONSTRAINT LOAN_ID_FK FOREIGN KEY (LOAN_ID) REFERENCES LOANS(ID)
/

--rollback DROP TABLE LOAN_PROLONGS

CREATE TABLE LOAN_PETITIONS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
CREATE_DATE TIMESTAMP     NOT NULL,
IP_ADDRESS VARCHAR(50)  NOT NULL,
CONSTRAINT C_LOAN_PETITIONS_PK PRIMARY KEY (ID)
)
/

CREATE INDEX IP_ADDRESS_IDX ON LOAN_PETITIONS(IP_ADDRESS)
/

--rollback DROP TABLE LOANS_PETITIONS

